obj-m += mymodule.o
 
all:
		make -C /lib/modules/5.2.8200225+/build M=/home/kau/jwbang/linux-5.2.8_final/mymodule modules
 
clean:
		make -C /lib/modules/5.2.8200225+/build M=/home/kau/jwbang/linux-5.2.8_final/mymodule clean
